=== ZARUJU/kaigitai/docs/schema/base/group.data.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Group data",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "name": { "type": "string", "minLength": 1 },
    "parent": { "type": ["string", "null"] },
    "category": { "type": "string", "minLength": 1 },
    "list_url": { "type": ["string", "null"], "format": "uri" },
    "official_url": { "type": "string", "format": "uri" }
  },
  "required": ["id", "name", "category", "official_url"],
  "additionalProperties": false
}

=== ZARUJU/kaigitai/data/group/3ac71474-e022-4d37-90a3-8884722bb092.json
{
  "id": "3ac71474-e022-4d37-90a3-8884722bb092",
  "name": "今後の中長期的な厚生労働科学研究の在り方に関する専門委員会",
  "parent": "47021f2b-2b2e-42d7-bf65-e11041f3bb3d",
  "category": "審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-kousei_127728.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-kousei_127728.html"
}

=== ZARUJU/kaigitai/data/group/0c9bb1e3-16fc-47f5-a14e-7aeba93e4dd5.json
{
  "id": "0c9bb1e3-16fc-47f5-a14e-7aeba93e4dd5",
  "name": "診療報酬基本問題小委員会",
  "parent": "7fed6615-074f-4b86-b78c-5b8eac7cb762",
  "category": "審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-chuo_128161.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-chuo_128161.html"
}

=== ZARUJU/kaigitai/data/group/67269093-a326-4481-881c-4086b2544805.json
{
  "id": "67269093-a326-4481-881c-4086b2544805",
  "name": "年金部会",
  "parent": "fea307f7-8dcc-4fa8-9869-03a1d2620cf2",
  "category": "国/審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-dokuritu_126775.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-dokuritu_126775.html"
}

=== ZARUJU/kaigitai/data/group/46eaa02e-41b6-407c-82de-02d404f31514.json
{
  "id": "46eaa02e-41b6-407c-82de-02d404f31514",
  "name": "確定拠出年金の運用に関する専門委員会",
  "parent": "2faa4696-edc0-4f4c-a09c-9842a91761e1",
  "category": "審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_413946.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_413946.html"
}

=== ZARUJU/kaigitai/data/group/82c58ce1-ba36-4062-8b6f-63eba9a883b7.json
{
  "id": "82c58ce1-ba36-4062-8b6f-63eba9a883b7",
  "name": "歯科医師臨床研修部会",
  "parent": "58e94bfa-2a3e-468a-b343-5a3c0bdfc66f",
  "category": "国/審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-idou_127796.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-idou_127796.html"
}

=== ZARUJU/kaigitai/data/group/3a63b873-7c23-477b-9910-83d0516ab7f4.json
{
  "id": "3a63b873-7c23-477b-9910-83d0516ab7f4",
  "name": "造血幹細胞移植委員会",
  "parent": "adbed643-3bef-4dc1-8c78-82f6d7c37d08",
  "category": "審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-kousei_127747.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-kousei_127747.html"
}

=== ZARUJU/kaigitai/data/group/32865dc2-67d3-487b-9038-1528fc158ebd.json
{
  "id": "32865dc2-67d3-487b-9038-1528fc158ebd",
  "name": "特定保険料納付申出等に係る承認基準専門委員会",
  "parent": "341ac0c3-43f3-44e6-b09f-f5734529cf07",
  "category": "国/審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_281775.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_281775.html"
}

=== ZARUJU/kaigitai/data/group/f7f5da8e-f2cc-4872-b808-3f75e22c9c1e.json
{
  "id": "f7f5da8e-f2cc-4872-b808-3f75e22c9c1e",
  "name": "匿名障害福祉及び障害児福祉情報等の提供に関する専門委員会",
  "parent": "99db420f-77a4-4fe9-a45f-f6cfb304bbaf",
  "category": "審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_126730_00008.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_126730_00008.html"
}
