=== ZARUJU/kaigitai/docs/schema/base/group.data.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Group data",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "name": { "type": "string", "minLength": 1 },
    "parent": { "type": ["string", "null"] },
    "category": { "type": "string", "minLength": 1 },
    "list_url": { "type": ["string", "null"], "format": "uri" },
    "official_url": { "type": "string", "format": "uri" }
  },
  "required": ["id", "name", "category", "official_url"],
  "additionalProperties": false
}

=== ZARUJU/kaigitai/data/group/a8ddb9d3-cb58-4188-aae2-8cc0ebe64804.json
{
  "id": "a8ddb9d3-cb58-4188-aae2-8cc0ebe64804",
  "name": "診療報酬調査専門組織（医療技術評価分科会）",
  "parent": "7fed6615-074f-4b86-b78c-5b8eac7cb762",
  "category": "審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-chuo_128167.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-chuo_128167.html"
}

=== ZARUJU/kaigitai/data/group/76a2df81-874c-4a76-94c5-e1012ffeed1a.json
{
  "id": "76a2df81-874c-4a76-94c5-e1012ffeed1a",
  "name": "受動喫煙対策専門委員会",
  "parent": "011ceda6-2a96-4818-b0ba-3d9b2530d20d",
  "category": "国/審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-kousei_127752_00008.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-kousei_127752_00008.html"
}

=== ZARUJU/kaigitai/data/group/57c4c8a4-5b8b-4612-9354-c87f4077ca30.json
{
  "id": "57c4c8a4-5b8b-4612-9354-c87f4077ca30",
  "name": "中央職業能力開発協会の在り方に関する専門委員会",
  "parent": "274c04eb-49b6-4bd4-b7a3-9ae7c67cc75d",
  "category": "審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-rousei_126988.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-rousei_126988.html"
}

=== ZARUJU/kaigitai/data/group/514c53e8-e028-41b7-a8c6-515c397d961e.json
{
  "id": "514c53e8-e028-41b7-a8c6-515c397d961e",
  "name": "児童館のあり方に関する検討ワーキンググループ",
  "parent": "9f96c8c9-bb48-447e-b29b-21fe38710fc8",
  "category": "国/審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_491253_1.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_491253_1.html"
}

=== ZARUJU/kaigitai/data/group/1ef4d890-4ebb-4fdc-8365-aa4954eee04d.json
{
  "id": "1ef4d890-4ebb-4fdc-8365-aa4954eee04d",
  "name": "人口構造の変化に関する特別部会",
  "parent": "78d683d4-6555-4961-aebf-39848aff5e09",
  "category": "国/審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_126705.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_126705.html"
}

=== ZARUJU/kaigitai/data/group/495d5b79-7455-4079-8b86-9b551abc6dc8.json
{
  "id": "495d5b79-7455-4079-8b86-9b551abc6dc8",
  "name": "電気事業及び石炭鉱業における争議行為の方法の規制に関する法律の在り方に関する部会",
  "parent": "b206a532-05aa-4a99-aa3f-1bfcb32a35f8",
  "category": "審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-rousei_214638.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-rousei_214638.html"
}

=== ZARUJU/kaigitai/data/group/34c50248-9d4d-420f-a1c1-3ba1f1b66d44.json
{
  "id": "34c50248-9d4d-420f-a1c1-3ba1f1b66d44",
  "name": "核酸等の第一種使用等に関する専門委員会",
  "parent": "e6ece248-8a8e-4cdd-b964-42804e3a3eb5",
  "category": "国/審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-kousei_429941_00002.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-kousei_429941_00002.html"
}

=== ZARUJU/kaigitai/data/group/680b2c6a-afc0-4a55-95e4-1ebb59473c05.json
{
  "id": "680b2c6a-afc0-4a55-95e4-1ebb59473c05",
  "name": "年金記録訂正分科会",
  "parent": "78d683d4-6555-4961-aebf-39848aff5e09",
  "category": "審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_238274.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_238274.html"
}
