=== ZARUJU/kaigitai/docs/schema/base/group.data.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Group data",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "name": { "type": "string", "minLength": 1 },
    "parent": { "type": ["string", "null"] },
    "category": { "type": "string", "minLength": 1 },
    "list_url": { "type": ["string", "null"], "format": "uri" },
    "official_url": { "type": "string", "format": "uri" }
  },
  "required": ["id", "name", "category", "official_url"],
  "additionalProperties": false
}

=== ZARUJU/kaigitai/data/group/cde53223-81ef-4a2b-bb41-134a46dc03a4.json
{
  "id": "cde53223-81ef-4a2b-bb41-134a46dc03a4",
  "name": "感染症・予防接種審査分科会（令和元年9月27日以前）",
  "parent": "f63e8af6-b433-4db5-86b3-f88c20a399fe",
  "category": "国/審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-shippei_127696.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-shippei_127696.html"
}

=== ZARUJU/kaigitai/data/group/d6636ea0-c7a4-486d-83cc-0dfdf5969c86.json
{
  "id": "d6636ea0-c7a4-486d-83cc-0dfdf5969c86",
  "name": "職業能力開発分科会若年労働者部会（旧勤労青少年部会）",
  "parent": "b206a532-05aa-4a99-aa3f-1bfcb32a35f8",
  "category": "審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-rousei_126987.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-rousei_126987.html"
}

=== ZARUJU/kaigitai/data/group/1c1d7c58-61d9-461c-ab33-1713fdb49671.json
{
  "id": "1c1d7c58-61d9-461c-ab33-1713fdb49671",
  "name": "クロイツフェルト・ヤコブ病等委員会",
  "parent": "adbed643-3bef-4dc1-8c78-82f6d7c37d08",
  "category": "国/審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-kousei_127749.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-kousei_127749.html"
}

=== ZARUJU/kaigitai/data/group/be5a225e-db15-4e9d-81f0-c9ebcaa41da3.json
{
  "id": "be5a225e-db15-4e9d-81f0-c9ebcaa41da3",
  "name": "障害者部会精神障害分会",
  "parent": "78d683d4-6555-4961-aebf-39848aff5e09",
  "category": "審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_126732.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_126732.html"
}

=== ZARUJU/kaigitai/data/group/42e6196a-06bc-426c-acea-fe746018524b.json
{
  "id": "42e6196a-06bc-426c-acea-fe746018524b",
  "name": "医療観察法部会",
  "parent": "78d683d4-6555-4961-aebf-39848aff5e09",
  "category": "国/審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_126733.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_126733.html"
}

=== ZARUJU/kaigitai/data/group/7bb5c751-5db6-48e9-8450-c92064d1b723.json
{
  "id": "7bb5c751-5db6-48e9-8450-c92064d1b723",
  "name": "保険医療材料等専門組織",
  "parent": "7fed6615-074f-4b86-b78c-5b8eac7cb762",
  "category": "審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-chuo_128167_00018.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-chuo_128167_00018.html"
}

=== ZARUJU/kaigitai/data/group/7ae80be5-f80e-4eef-b97e-d964983d92d2.json
{
  "id": "7ae80be5-f80e-4eef-b97e-d964983d92d2",
  "name": "歯科医師国家試験出題基準改定部会",
  "parent": "58e94bfa-2a3e-468a-b343-5a3c0bdfc66f",
  "category": "国/審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-idou_341268.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-idou_341268.html"
}

=== ZARUJU/kaigitai/data/group/a84aa824-ad7c-4210-965d-6cc0ef80094c.json
{
  "id": "a84aa824-ad7c-4210-965d-6cc0ef80094c",
  "name": "児童虐待等要保護事例の検証に関する専門委員会",
  "parent": "1c790c4b-30dc-4cb3-9a1d-1383b8125d19",
  "category": "国/審議会(子)",
  "list_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_126713.html",
  "official_url": "https://www.mhlw.go.jp/stf/shingi/shingi-hosho_126713.html"
}
